### PR TITLE
New util method to add a prefix or suffix to ids

### PR DESCRIPTION
**Pull request by markusstraub**
I often need to combine GTFS feeds and to avoid conflicts (e.g. same `route_id` in two feeds) it is sometimes useful to simply add a prefix or postfix to all those ids. I hope this is useful for you as well?

### CODE REVIEW

**Comment by araichev** [comment]
This feature looks good, @markusstraub . I'm going to pull it into a feature branch, make a few tweaks, then push the feature branch back for your comments.

**Comment by araichev** [comment]
How's that rendition of your code (in feature/extend-id) @markusstraub ?

**Comment by markusstraub** [comment]
Looks great!

**Comment by araichev** [comment]
Thanks @markusstraub for your contribution, which i've now included in Release 6.1.0.

**Pull request merged**
