### PR TITLE
Added gdf compatibility to `build_geometry_by_shape`

### PR DESCRIPTION
**Pull request by diegoperezalvarez**
Hello,

First of all - this is a great project! I'm starting to work with GTFS feeds regularly at my work, so I'm looking for a platform on which to do it easily. I started using your repository and it has been a huge help in understanding GTFS and working with them in an uncomplicated way.

I'd like to do this more regularly, perhaps with more substantive changes, and possibly help out, but I would need a hand as I am quite new to git management. As I haven't done any major repository editing / implementation before, I thought I'd submit a little PR here. Let me know if this fits with what you're looking for.

___

I've added compatibility and tests for returning a GeoDataFrame in the build_geometry_by_shape function. This allows users to filter the shapes as a GeoDataFrame with a 'geometry' column when the as_gdf parameter is set to True. If as_gdf is False (default), the function will return the shapes as a dictionary.

### CODE REVIEW

**Comment by diegoperezalvarez** [comment]
Realise I was trying to PR the master, should really be the dev branch, mb.

**Comment by araichev** [comment]
Thanks for your praise and contribution @diegoperezalvarez . It's always good to see. In this case, i beat you to the feature in release 7.0.0 with the function [get_shapes](https://mrcagney.github.io/gtfs_kit_docs/#gtfs_kit.shapes.get_shapes), so i'll close this PR now.

**Comment by diegoperezalvarez** [comment]
No problem, thank you Alex 👍

I did note that [get_shapes](https://mrcagney.github.io/gtfs_kit_docs/#gtfs_kit.shapes.get_shapes) will form the shapes and add them into a geodataframe with the `as_gdf` kwarg - however - [build_geometry_by_shape](https://mrcagney.github.io/gtfs_kit_docs/#gtfs_kit.shapes.build_geometry_by_shape) returns a dict by default, even though the function uses a geodataframe internally, hence the PR. Honestly, no worries either way though.

All the best,

Diego

**Comment by araichev** [comment]
Hi @diegoperezalvarez , yes i should've clarified that `build_geometry_by_shape` is an internal convenience function for a few other functions and does essentially the same thing a `get_shapes` but returns a dictionary instead. Now that you bring it up, it might be better to delete the function and shrink the API. I'll look into that for next release.

**Pull request closed without merging**
